name: expenseanalyzer


services:
  postgres:
    image: postgres:15-alpine
    container_name: prod-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: expense_db
    ports:
      - "5433:5432" # Map to 5433 so it doesn't conflict with local dev DB on 5432
    volumes:
      - prod-postgres-data:/var/lib/postgresql/data
    networks:
      - prod-network

  jenkins:
    build: ./jenkins
    container_name: prod-jenkins
    user: root # Needed to run Docker inside Jenkins
    environment:
      - JAVA_OPTS=-Xmx1024m
    ports:
      - "9090:8080" # Access Jenkins UI on http://localhost:9090
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Allows Jenkins to build Docker containers
    networks:
      - prod-network

  config-server:
    build: ./config-server
    container_name: prod-config-server
    restart: on-failure
    environment:
      - JAVA_OPTS=-Xmx256m
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/expense_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - LOG_DIR=/logs
    volumes:
      - D:/DevStorage/Logs:/logs
    networks:
      - prod-network

  discovery-server:
    build: ./discovery-server
    container_name: prod-discovery-server
    ports:
      - "8761:8761"
    restart: on-failure
    environment:
      - JAVA_OPTS=-Xmx256m
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - LOG_DIR=/logs
    volumes:
      - D:/DevStorage/Logs:/logs
    depends_on:
      - config-server
    networks:
      - prod-network

  auth-service:
    build: ./auth-service
    container_name: prod-auth-service
    restart: on-failure
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/expense_db
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - LOG_DIR=/logs
    volumes:
      - D:/DevStorage/Logs:/logs
    depends_on:
      - postgres
      - discovery-server
    networks:
      - prod-network

  expense-service:
    build: ./expense-service
    container_name: prod-expense-service
    restart: on-failure
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/expense_db
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - LOG_DIR=/logs
    volumes:
      - D:/DevStorage/Logs:/logs
    depends_on:
      - postgres
      - discovery-server
    networks:
      - prod-network

  notification-service:
    build: ./notification-service
    container_name: prod-notification-service
    restart: on-failure
    environment:
      - JAVA_OPTS=-Xmx256m
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - LOG_DIR=/logs
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - D:/DevStorage/Logs:/logs
    depends_on:
      - discovery-server
    networks:
      - prod-network

  vision-service:
    build: ./vision-service
    container_name: prod-vision-service
    restart: on-failure
    environment:
      - JAVA_OPTS=-Xmx256m
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - LOG_DIR=/logs
    volumes:
      - D:/DevStorage/Logs:/logs
    depends_on:
      - discovery-server
    networks:
      - prod-network

  frontend:
    build: ./frontend
    container_name: prod-frontend
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8081
      - EXPENSE_SERVICE_URL=http://expense-service:8080
    ports:
      - "4000:3000" # Map to 4000 so it doesn't conflict with local dev frontend
    depends_on:
      - auth-service
      - expense-service
    networks:
      - prod-network

networks:
  prod-network:
    driver: bridge

volumes:
  prod-postgres-data:
  jenkins-data:
