spring.application.name=expense-service
spring.config.import=optional:configserver:http://localhost:8888
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
jwt.secret=4f6a7d8c2e1b4f6a7d8c2e1b4f6a7d8c2e1b
jwt.expiration=86400000

logging.file.name=${LOG_DIR:logs}/${spring.application.name}.log
