CREATE SCHEMA IF NOT EXISTS config;
CREATE TABLE IF NOT EXISTS config.PROPERTIES (
    APPLICATION VARCHAR(255),
    PROFILE VARCHAR(255),
    LABEL VARCHAR(255),
    KEY VARCHAR(255),
    VALUE VARCHAR(255)
);
